<a href="https://colab.research.google.com/github/Jaswanth62/MEDICINE_RECOMMEND_REPO/blob/main/discover_disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/df_ans.csv")
df=df.sample(frac=1)
df.head(10)

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
77,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Arthritis
358,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypothyroidism
149,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,Migraine
650,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal
190,0,1,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,Acne
544,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,Migraine
188,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Vertigo
829,0,1,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,Acne
253,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hypothyroidism
871,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergies

In [ ]:
y=pd.get_dummies(df["prognosis"])
y

,Acne,Allergies,Arthritis,Diabetes,Fungal,Hypertension,Hyperthyroidism,Hypothyroidism,Migraine,Vertigo
77,0,0,1,0,0,0,0,0,0,0
358,0,0,0,0,0,0,0,1,0,0
149,0,0,0,0,0,0,0,0,1,0
650,0,0,0,0,1,0,0,0,0,0
190,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
801,0,1,0,0,0,0,0,0,0,0
1076,0,0,0,0,0,0,1,0,0,0
307,0,0,0,0,1,0,0,0,0,0
474,0,0,1,0,0,0,0,0,0,0
208,0,0,0,0,1,0,0,0,0,0

In [ ]:
x=df.drop(["prognosis"],axis=1)
x

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
77,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
358,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
149,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
650,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
190,0,1,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
801,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1076,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
307,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
474,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
208,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [ ]:
x_train

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
1153,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1127,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1039,0,1,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
480,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
374,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
725,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
439,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
982,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
780,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
y_train

,Acne,Allergies,Arthritis,Diabetes,Fungal,Hypertension,Hyperthyroidism,Hypothyroidism,Migraine,Vertigo
1153,0,0,0,0,0,1,0,0,0,0
1127,0,0,1,0,0,0,0,0,0,0
1039,1,0,0,0,0,0,0,0,0,0
480,0,0,0,0,0,0,0,0,0,1
374,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
385,0,0,0,0,0,0,0,0,0,1
725,0,0,0,0,0,0,0,1,0,0
439,0,0,0,0,0,1,0,0,0,0
982,0,0,0,1,0,0,0,0,0,0
780,0,0,0,0,1,0,0,0,0,0

In [ ]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
# model = Sequential()
# model.add(Dense(133,activation="relu"))
# model.add(Dense(120,activation="relu"))  # Hidden layer
# model.add(Dense(10,activation="softmax")) # Output layer

# model.compile(optimizer='sgd', loss=tf.keras.losses.CategoricalCrossentropy(), metrics=["accuracy"])
# model.fit(x_train,y_train,epochs= 50)


model = tf.keras.models.Sequential([tf.keras.layers.Dense(133, activation=tf.nn.relu),
                                    tf.keras.layers.Dense(64, activation=tf.nn.relu),
                                    tf.keras.layers.Dense(32, activation=tf.nn.relu),
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax)])
model.compile(loss=tf.keras.losses.CategoricalCrossentropy(), optimizer='adam', metrics=['accuracy'])
model.fit(x_train,y_train,epochs= 50)

Epoch 1/50
27/27 [==============================] - 1s 2ms/step - loss: 1.8472 - accuracy: 0.6238
Epoch 2/50
27/27 [==============================] - 0s 2ms/step - loss: 0.7291 - accuracy: 0.9988
Epoch 3/50
27/27 [==============================] - 0s 2ms/step - loss: 0.1163 - accuracy: 1.0000
Epoch 4/50
27/27 [==============================] - 0s 2ms/step - loss: 0.0179 - accuracy: 1.0000
Epoch 5/50
27/27 [==============================] - 0s 2ms/step - loss: 0.0078 - accuracy: 1.0000
Epoch 6/50
27/27 [==============================] - 0s 2ms/step - loss: 0.0049 - accuracy: 1.0000
Epoch 7/50
27/27 [==============================] - 0s 2ms/step - loss: 0.0035 - accuracy: 1.0000
Epoch 8/50
27/27 [==============================] - 0s 2ms/step - loss: 0.0026 - accuracy: 1.0000
Epoch 9/50
27/27 [==============================] - 0s 2ms/step - loss: 0.0020 - accuracy: 1.0000
Epoch 10/50
27/27 [==============================] - 0s 2ms/step - loss: 0.0016 - accuracy: 1.0000
Epoch 11/50
27/27 [==============================] - 0s 2ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 12/50
27/27 [==============================] - 0s 2ms/step - loss: 0.0011 - accuracy: 1.0000
Epoch 13/50
27/27 [==============================] - 0s 2ms/step - loss: 9.5742e-04 - accuracy: 1.0000
Epoch 14/50
27/27 [==============================] - 0s 2ms/step - loss: 8.1980e-04 - accuracy: 1.0000
Epoch 15/50
27/27 [==============================] - 0s 2ms/step - loss: 7.1184e-04 - accuracy: 1.0000
Epoch 16/50
27/27 [==============================] - 0s 2ms/step - loss: 6.2522e-04 - accuracy: 1.0000
Epoch 17/50
27/27 [==============================] - 0s 2ms/step - loss: 5.5315e-04 - accuracy: 1.0000
Epoch 18/50
27/27 [==============================] - 0s 2ms/step - loss: 4.9380e-04 - accuracy: 1.0000
Epoch 19/50
27/27 [==============================] - 0s 2ms/step - loss: 4.4349e-04 - accuracy: 1.0000
Epoch 20/50
27/27 [==============================] - 0s 2ms/step - loss: 3.9988e-04 - accuracy: 1.0000
Epoch 21/50
27/27 [==============================] - 0s 2ms/step - loss: 3.6281e-04 - accuracy: 1.0000
Epoch 22/50
27/27 [==============================] - 0s 2ms/step - loss: 3.3078e-04 - accuracy: 1.0000
Epoch 23/50
27/27 [==============================] - 0s 2ms/step - loss: 3.0242e-04 - accuracy: 1.0000
Epoch 24/50
27/27 [==============================] - 0s 2ms/step - loss: 2.7787e-04 - accuracy: 1.0000
Epoch 25/50
27/27 [==============================] - 0s 2ms/step - loss: 2.5577e-04 - accuracy: 1.0000
Epoch 26/50
27/27 [==============================] - 0s 2ms/step - loss: 2.3651e-04 - accuracy: 1.0000
Epoch 27/50
27/27 [==============================] - 0s 2ms/step - loss: 2.1895e-04 - accuracy: 1.0000
Epoch 28/50
27/27 [==============================] - 0s 3ms/step - loss: 2.0336e-04 - accuracy: 1.0000
Epoch 29/50
27/27 [==============================] - 0s 2ms/step - loss: 1.8924e-04 - accuracy: 1.0000
Epoch 30/50
27/27 [==============================] - 0s 3ms/step - loss: 1.7656e-04 - accuracy: 1.0000
Epoch 31/50
27/27 [==============================] - 0s 3ms/step - loss: 1.6511e-04 - accuracy: 1.0000
Epoch 32/50
27/27 [==============================] - 0s 2ms/step - loss: 1.5459e-04 - accuracy: 1.0000
Epoch 33/50
27/27 [==============================] - 0s 2ms/step - loss: 1.4508e-04 - accuracy: 1.0000
Epoch 34/50
27/27 [==============================] - 0s 2ms/step - loss: 1.3630e-04 - accuracy: 1.0000
Epoch 35/50
27/27 [==============================] - 0s 3ms/step - loss: 1.2844e-04 - accuracy: 1.0000
Epoch 36/50
27/27 [==============================] - 0s 3ms/step - loss: 1.2122e-04 - accuracy: 1.0000
Epoch 37/50
27/27 [==============================] - 0s 3ms/step - loss: 1.1466e-04 - accuracy: 1.0000
Epoch 38/50
27/27 [==============================] - 0s 3ms/step - loss: 1.0843e-04 - accuracy: 1.0000
Epoch 39/50
27/27 [==============================] - 0s 3ms/step - loss: 1.0277e-04 - accuracy: 1.0000
Epoch 40/50
27/27 [==============================] - 0s 2ms/step - loss: 9.7484e-05 - accuracy: 1.0000
Epoch 41/50
27/27 [==============================] - 0s 2ms/step - loss: 9.2565e-05 - accuracy: 1.0000
Epoch 42/50
27/27 [==============================] - 0s 3ms/step - loss: 8.8019e-05 - accuracy: 1.0000
Epoch 43/50
27/27 [==============================] - 0s 2ms/step - loss: 8.3816e-05 - accuracy: 1.0000
Epoch 44/50
27/27 [==============================] - 0s 2ms/step - loss: 7.9853e-05 - accuracy: 1.0000
Epoch 45/50
27/27 [==============================] - 0s 3ms/step - loss: 7.6181e-05 - accuracy: 1.0000
Epoch 46/50
27/27 [==============================] - 0s 2ms/step - loss: 7.2771e-05 - accuracy: 1.0000
Epoch 47/50
27/27 [==============================] - 0s 2ms/step - loss: 6.9551e-05 - accuracy: 1.0000
Epoch 48/50
27/27 [==============================] - 0s 3ms/step - loss: 6.6532e-05 - accuracy: 1.0000
Epoch 49/50
27/27 [==============================] - 0s 3ms/step - loss: 6.3701e-05 - accuracy: 1.0000
Epoch 50/50
27/27 [==============================] - 0s 2ms/step - loss: 6.1014e-05 - accuracy: 1.0000

In [ ]:
x_train
# x_train = x_train.drop('Unnamed: 133', axis=1)
x_train

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
1153,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1127,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1039,0,1,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
480,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
374,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
725,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
439,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
982,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
780,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
x_test

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
551,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
613,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
981,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
935,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
533,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
312,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
568,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1176,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
y_test

,Acne,Allergies,Arthritis,Diabetes,Fungal,Hypertension,Hyperthyroidism,Hypothyroidism,Migraine,Vertigo
551,0,0,0,0,0,0,0,1,0,0
613,0,0,0,0,0,1,0,0,0,0
981,0,1,0,0,0,0,0,0,0,0
935,0,0,0,0,0,0,0,1,0,0
37,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
995,0,0,0,0,0,0,0,1,0,0
533,0,0,0,0,0,1,0,0,0,0
312,0,1,0,0,0,0,0,0,0,0
568,0,0,0,0,0,0,1,0,0,0
1176,0,0,0,0,0,0,1,0,0,0

In [ ]:
score = model.evaluate(x_test,y_test)
print("ACCURACY : ",score)

12/12 [==============================] - 0s 1ms/step - loss: 5.8113e-05 - accuracy: 1.0000
ACCURACY :  [5.811348819406703e-05, 1.0]

In [ ]:
i=model.predict([[0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])
i

1/1 [==============================] - 0s 71ms/step

array([[0.3352943 , 0.03467206, 0.04457178, 0.0202474 , 0.5063746 ,
        0.03630866, 0.00787563, 0.00429954, 0.0021878 , 0.00816829]],
      dtype=float32)

In [ ]:
i=model.predict([[1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])
i

1/1 [==============================] - 0s 35ms/step

array([[2.4657356e-05, 7.2592247e-06, 1.3787609e-04, 3.4569539e-06,
        9.9965215e-01, 1.2831784e-04, 2.6175228e-05, 5.2230797e-07,
        6.3251200e-08, 1.9427473e-05]], dtype=float32)